# vim: fml& fdn& fdm=marker fmr=〈,〉

[[ -n $PROFILE_ZSH ]] && zmodload zsh/zprof

setopt EXTENDED_GLOB

# OMZ
DISABLE_AUTO_UPDATE="true"
HYPHEN_INSENSITIVE="true"
DISABLE_LS_COLORS="true" # use plugin
DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="true"

# Antidote 〈

antidote=/opt/homebrew/opt/antidote/share/antidote

zstyle ':antidote:bundle' use-friendly-names 'yes'

# Set the root name of the plugins files (.txt and .zsh) antidote will use.
zsh_plugins=${ZDOTDIR:-~}/.zsh_plugins

# Ensure the .zsh_plugins.txt file exists so you can add plugins.
[[ -f ${zsh_plugins}.txt ]] || touch ${zsh_plugins}.txt

# Lazy-load antidote from its functions directory.
fpath=(${antidote}/functions $fpath)
autoload -Uz antidote

# Generate a new static file whenever .zsh_plugins.txt is updated.
if [[ ! ${zsh_plugins}.zsh -nt ${zsh_plugins}.txt ]]; then
  antidote bundle <${zsh_plugins}.txt >|${zsh_plugins}.zsh
fi

# Source your static plugins file.
source ${zsh_plugins}.zsh

# Antidote 〉

# Custom
for f in "${MDX_DOT_DIR}/zsh/zshrc.d"/*.zsh; do
  source $f
done

# Prompt
eval "$(starship init zsh)"

[[ -n $PROFILE_ZSH ]] && zprof >/tmp/zprof.txt
